#!/bin/bash
# 需要先设置免密登录

#ansible不知道如何查看输出
echo '请务必修改文件路径'
ansible all -m script -a "/root/auto_init_final/init"
ansible all -a "reboot"
ansible server -m script -a "/root/auto_init_final/server"
ansible other -m script -a "/root/auto_init_final/client"
